_start:
    spush 'H'
    scall putchar
    sclr
    spush 'e'
    scall putchar
    sclr
    spush 'l'
    scall putchar
    sclr
    spush 'l'
    scall putchar
    sclr
    spush 'o'
    scall putchar
    sclr
    spush 0x20
    scall putchar
    sclr
    spush ','
    scall putchar
    sclr
    spush 'W'
    scall putchar
    sclr
    spush 'o'
    scall putchar
    sclr
    spush 'r'
    scall putchar
    sclr
    spush 'l'
    scall putchar
    sclr
    spush 'd'
    scall putchar
    sclr
    spush '!'
    scall putchar
    sclr